spring:
  kafka:
    bootstrap-servers: localhost:9092
  consumer:
    group-id: my-group
    topic: test-topic
    auto-offset-reset: earliest
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
file:
  path: